export const FETCH_PROJECTS_REQUEST = 'FETCH_PROJECTS_REQUEST';
export const FETCH_PROJECTS_FAILED = 'FETCH_PROJECTS_FAILED';
export const FETCH_PROJECTS_SUCCESS = 'FETCH_PROJECTS_SUCCESS';

export const FETCH_PROJECT_REQUEST = 'FETCH_PROJECT_REQUEST';
export const FETCH_PROJECT_FAILED = 'FETCH_PROJECT_FAILED';
export const FETCH_PROJECT_SUCCESS = 'FETCH_PROJECT_SUCCESS';

export const FETCH_BUILDS_REQUEST = 'FETCH_BUILDS_REQUEST';
export const FETCH_BUILDS_FAILED = 'FETCH_BUILDS_FAILED';
export const FETCH_BUILDS_SUCCESS = 'FETCH_BUILDS_SUCCESS';

export const FETCH_BUILD_CHART_REQUEST = 'FETCH_BUILD_CHART_REQUEST';
export const FETCH_BUILD_CHART_FAILED = 'FETCH_BUILD_CHART_FAILED';
export const FETCH_BUILD_CHART_SUCCESS = 'FETCH_BUILD_CHART_SUCCESS';

export const SOCKET_CONNECT = 'SOCKET_CONNECT';
export const SOCKET_CONNECT_SUCCESS = 'SOCKET_CONNECT_SUCCESS';
export const SOCKET_CONNECT_FAILED = 'SOCKET_CONNECT_FAILED';
export const SOCKET_DISCONNECTED = 'SOCKET_DISCONNECTED';
export const SOCKET_RECEIVE_STATE = 'SOCKET_RECEIVE_STATE';

export const SET_FILTER = 'SET_FILTER';
